/** Independent Validation Agent /root/validation. No production metric/ledger imports. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {execFileSync,spawnSync} from 'node:child_process';
import {DEFAULT,LIMITS,MACHINE,MU0,KEV,geometry,basis,equilibrium,runShot} from '../../physics/engine.ts';
import {root,fingerprint,hash} from '../../tools/workflow.mjs';
const spec=JSON.parse(fs.readFileSync(path.join(root,'specs/m02.json'))),T=spec.thresholds;
const sourceHash=fingerprint(), records=[];
const mu=4*Math.PI*1e-7,kev=1.602176634e-16,alpha=.4,B=.2,A=alpha/mu,Ra=1.66,pa=.5;
const max=(xs)=>Math.max(...xs), rel=(a,b)=>Math.abs(a-b)/Math.max(Math.abs(b),1e-300);
const plain=x=>JSON.parse(JSON.stringify(x));
function le(x,t,label){assert.ok(Number.isFinite(x)&&x<=t,`${label}: ${x} > ${t}`);}
function order(a,b){return Math.log2(a/b);}
function orderOK(p,label){assert.ok(Number.isFinite(p)&&p>=T.fluxOrder[0]&&p<=T.fluxOrder[1],`${label}: order ${p}`);}
async function check(checkId,fn){let status='PASS',measurements;try{measurements=await fn();}catch(e){status='FAIL';measurements={failure:e.message,stack:e.stack};}const evidence=`validation/evidence/${checkId}.json`;const record={checkId,status,testCommandOrName:`node --experimental-strip-types validation/independent/m02.mjs (${checkId})`,thresholds:T,measurements,sourceHash,runtimeVersion:process.version,artifactPaths:[evidence]};fs.writeFileSync(path.join(root,evidence),JSON.stringify(record,null,2)+'\n');records.push({name:checkId,status,evidence,sha256:hash(fs.readFileSync(path.join(root,evidence)))});console.log(checkId+': '+status+(status==='FAIL'?' '+measurements.failure:''));}
function exact(r,z){return pa-alpha/8*(r*r-Ra*Ra)**2-B/2*z*z;}
function lap(p,g,i,j){const k=j*g.n+i;return (p[k+1]-2*p[k]+p[k-1])/g.dr**2-(p[k+1]-p[k-1])/(2*g.R[i]*g.dr)+(p[k+g.n]-2*p[k]+p[k-g.n])/g.dz**2;}
const rectangles=[];
function rectangle(n){const R=Array.from({length:n},(_,i)=>1+i*((2.32-1)/(n-1))),Z=Array.from({length:n},(_,j)=>-.66+j*((.66-(-.66))/(n-1))),dr=R[1]-R[0],dz=Z[1]-Z[0],mask=new Uint8Array(n*n);let volume=0,C=0,D=0;const u=[],v=[],expected=[];for(let j=0;j<n;j++)for(let i=0;i<n;i++){const k=j*n+i;u[k]=pa/A-mu/8*(R[i]**2-Ra**2)**2;v[k]=-(Z[j]**2)/2;expected[k]=exact(R[i],Z[j]);if(i&&j&&i<n-1&&j<n-1){mask[k]=1;volume+=2*Math.PI*R[i]*dr*dz;C+=R[i]*dr*dz;D+=dr*dz/(mu*R[i]);}}const g={n,R,Z,dr,dz,mask,volume,C,D};const solved=basis(g,{u,v}),psi=Array.from(solved.u,(x,k)=>A*x+B*solved.v[k]);return {g,solved,psi,expected};}
await check('M02-REGRESSION-EXACT',()=>{
 const bytes=fs.readFileSync(path.join(root,'experiments/baseline/m01-regression.json')),manifest=JSON.parse(fs.readFileSync(path.join(root,'experiments/baseline/m01-regression-manifest.json'))),fixtures=JSON.parse(bytes);assert.equal(hash(bytes),manifest.fixtureSha256);assert.equal(manifest.sourceHash,'9dde261db38c18469902fd7dc02c80978f417a824c2aa159b573282bf63b84c7');assert.equal(process.version,manifest.runtimeVersion);const rows=[];
 for(const f of fixtures.cases){const g=geometry(f.c),b=basis(g),shot=runShot(f.c,g);assert.deepEqual(plain(g),f.g);assert.deepEqual(plain(b),f.b);assert.deepEqual(shot,f.shot);const checkpoints=[0,1,2.5,4,5].map(t=>{const s=shot.samples.find(x=>x.t===t);return equilibrium(b,s.ip,f.c.bt,s.pressure);});assert.deepEqual(checkpoints,f.equilibria);let count=0;assert.deepEqual(runShot(f.c,g,.002,undefined,s=>{assert.ok(Object.isFrozen(s));count++;try{s.postN=0;}catch{}}),shot);assert.equal(count,2500);rows.push({case:f.name,exact:true,observerSteps:count});}
 return {fixtureSha256:hash(bytes),sourceBeforeM02:manifest.sourceHash,rows};
});
await check('M02-OPERATOR-PROVENANCE',()=>{const engine=fs.readFileSync(path.join(root,'physics/engine.ts'),'utf8'),verification=fs.readFileSync(path.join(root,'physics/verification.ts'),'utf8');assert.equal((engine.match(/export function basis\(/g)||[]).length,1);assert.match(verification,/basis\(/);assert.match(engine,/u\[k\]\+=1\.7/);assert.match(engine,/v\[k\]\+=1\.7/);assert.match(engine,/residual<1e-8/);const g=geometry(DEFAULT);assert.throws(()=>basis(g,{u:[],v:[]}));assert.throws(()=>basis(g,{u:Array(g.n*g.n).fill(NaN),v:Array(g.n*g.n).fill(0)}));return {productionSolver:'physics/engine.ts::basis',analyticCall:'independent rectangle -> same imported basis(g,{u,v})',defaultCall:'geometry(DEFAULT) -> same basis(g)',sourceSha256:hash(engine),note:'Source inspected: same SOR sweep and residual loop; only inactive-node initialization differs. Exact old arrays and iteration count checked by regression.'};});
await check('M02-ANALYTIC-IDENTITY',()=>{assert.equal(MU0,mu);assert.equal(KEV,kev);const rows=[];for(const n of [33,65,129]){const q=rectangle(n);rectangles.push(q);let worst=0;for(let j=1;j<n-1;j++)for(let i=1;i<n-1;i++){const expected=alpha*q.g.dr**2/4,actual=lap(q.expected,q.g,i,j)+alpha*q.g.R[i]**2+B;worst=Math.max(worst,rel(actual,expected));}le(worst,T.truncationIdentityRelative,'quartic stencil identity');rows.push({n,expectedTruncation:alpha*q.g.dr**2/4,worstRelative:worst});}return {rows,derivation:'psi_R=-alpha R(R²-Ra²)/2; psi_RR=-alpha(3R²-Ra²)/2; psi_ZZ=-B. Delta*psi=-alpha R²-B. Central stencil residual=alpha dR²/4.',dimensions:{psi:'Wb',alpha:'Wb/m^4',B:'Wb/m^2',A:'Pa/Wb',j:'A/m^2',pressure:'Pa'},source:'https://arxiv.org/pdf/1906.05534',sourceRead:'Independent reviewer read v1 equations 10-12 and static-limit construction; SI signs differentiated independently.'};});
const gridConvergence=[];
await check('M02-RECT-FLUX',()=>{for(const {g,solved,psi,expected} of rectangles){let ss=0,weight=0,inf=0;for(let k=0;k<psi.length;k++)if(g.mask[k]){const w=2*Math.PI*g.R[k%g.n]*g.dr*g.dz,d=psi[k]-expected[k];ss+=w*d*d;weight+=w;inf=Math.max(inf,Math.abs(d));}const row={n:g.n,Linf:inf/pa,L2:Math.sqrt(ss/weight)/pa,basisResidual:solved.residual,iterations:solved.iterations};assert.ok(row.Linf>0&&row.L2>0);assert.ok(solved.residual<T.basisResidual);gridConvergence.push(row);}for(let i=1;i<gridConvergence.length;i++){const row=gridConvergence[i],old=gridConvergence[i-1];row.orderLinf=order(old.Linf,row.Linf);row.orderL2=order(old.L2,row.L2);orderOK(row.orderLinf,'flux Linf');orderOK(row.orderL2,'flux L2');}assert.equal(gridConvergence.length,3);le(gridConvergence[2].Linf,T.fineFluxLinfRelative,'fine Linf');le(gridConvergence[2].L2,T.fineFluxL2Relative,'fine L2');return {gridConvergence};});
function axis(psi,g){let k=0;for(let x=1;x<psi.length;x++)if(psi[x]>psi[k])k=x;const i=k%g.n,j=Math.floor(k/g.n),f=psi[k];const interpolate=(left,right,h)=>{const denom=left-2*f+right;return {shift:(left-right)*h/(2*denom),peakDelta:-((right-left)**2)/(8*denom)};};const r=interpolate(psi[k-1],psi[k+1],g.dr),z=interpolate(psi[k-g.n],psi[k+g.n],g.dz);return {gridR:g.R[i],gridZ:g.Z[j],gridPeak:f,R:g.R[i]+r.shift,Z:g.Z[j]+z.shift,peak:f+r.peakDelta+z.peakDelta};}
await check('M02-RECT-BOUNDARY-AXIS',()=>{const rows=rectangles.map(({g,psi,expected})=>{let boundary=0;const edge=[];for(let k=0;k<psi.length;k++)if(!g.mask[k]){boundary=Math.max(boundary,Math.abs(psi[k]-expected[k])/pa);edge.push(expected[k]);}le(boundary,T.boundaryRelative,'rectangle boundary');const ax=axis(psi,g);if(g.n===129){le(Math.abs(ax.R-Ra)/g.dr,T.fineAxisErrorGridSpacings,'axis R');le(Math.abs(ax.Z)/g.dz,T.fineAxisErrorGridSpacings,'axis Z');le(rel(ax.peak,pa),T.finePeakRelative,'peak');}return {n:g.n,boundaryRelative:boundary,edgeMinimum:Math.min(...edge),edgeMaximum:max(edge),axis:ax};});return {rows};});
await check('M02-RECT-CURRENT-PRESSURE',()=>{const exactI=1.32*(A/2*(2.32**2-1)+(B/mu)*Math.log(2.32)),vol=2*Math.PI*1.32*(2.32**2-1)/2;const radial=r=>pa*r*r/2-alpha/48*(r*r-Ra*Ra)**3;const intR=(2.32**2-1)/2;const exactP=A*2*Math.PI*(1.32*(radial(2.32)-radial(1))-B/2*(2*.66**3/3)*intR)/vol;const rows=[];for(const {g,psi,expected} of rectangles){let ji=0,pmean=0,jerr=0,exerr=0,identity=0,pinf=0,jscale=0;for(let j=0;j<g.n;j++)for(let i=0;i<g.n;i++){const k=j*g.n+i,r=g.R[i],ref=A*r+B/(mu*r),w=(i===0||i===g.n-1?.5:1)*(j===0||j===g.n-1?.5:1)*g.dr*g.dz;ji+=w*ref;pmean+=w*2*Math.PI*r*A*psi[k];if(g.mask[k]){const num=-lap(psi,g,i,j)/(mu*r),errExact=-lap(expected,g,i,j)/(mu*r)-ref,expectedErr=-alpha*g.dr**2/(4*mu*r);jerr=Math.max(jerr,Math.abs(num-ref));exerr=Math.max(exerr,Math.abs(errExact));identity=Math.max(identity,rel(errExact,expectedErr));jscale=Math.max(jscale,ref);pinf=Math.max(pinf,Math.abs(A*psi[k]-A*expected[k])/(A*pa));}}const row={n:g.n,currentDerivativeRelative:jerr/jscale,exactDerivativeError:exerr,derivativeIdentityRelative:identity,currentIntegral:ji,exactCurrentIntegral:exactI,currentIntegralRelative:rel(ji,exactI),meanPressure:pmean/vol,exactMeanPressure:exactP,meanPressureRelative:rel(pmean/vol,exactP),pressurePointwiseRelative:pinf};le(identity,T.truncationIdentityRelative,'derivative truncation identity');rows.push(row);}for(let i=1;i<rows.length;i++){const r=rows[i],p=rows[i-1];r.exactDerivativeOrder=order(p.exactDerivativeError,r.exactDerivativeError);orderOK(r.exactDerivativeOrder,'exact derivative error');assert.ok(r.currentIntegralRelative<p.currentIntegralRelative);assert.ok(r.meanPressureRelative<p.meanPressureRelative);}const fine=rows.at(-1);le(fine.currentDerivativeRelative,T.fineCurrentPointwiseRelative,'current derivative');le(fine.currentIntegralRelative,T.fineIntegratedCurrentRelative,'current integral');le(fine.meanPressureRelative,T.fineMeanPressureRelative,'pressure integral');le(fine.pressurePointwiseRelative,T.finePressurePointwiseRelative,'pressure conversion');return {rows,quadrature:'Independent complete-domain composite trapezoid of analytic current and numerical pressure; continuum polynomial/log reference integrals; no C/D or basis averages used.'};});
function distances(g,c){const curve=Array.from({length:4097},(_,k)=>{const t=2*Math.PI*k/4096;return [1.66+.66*Math.cos(t+Math.asin(c.delta)*Math.sin(t)),c.kappa*.66*Math.sin(t)];}),links=[];for(let j=0;j<g.n;j++)for(let i=0;i<g.n;i++){const k=j*g.n+i;if(i+1<g.n&&g.mask[k]!==g.mask[k+1])links.push([(g.R[i]+g.R[i+1])/2,g.Z[j]]);if(j+1<g.n&&g.mask[k]!==g.mask[k+g.n])links.push([g.R[i],(g.Z[j]+g.Z[j+1])/2]);}const directed=(a,b)=>{let worst=0;for(const p of a){let best=Infinity;for(const q of b)best=Math.min(best,(p[0]-q[0])**2+(p[1]-q[1])**2);worst=Math.max(worst,Math.sqrt(best));}return worst;};return {curveToInterface:directed(curve,links),interfaceToCurve:directed(links,curve),curveIntervals:4096,interfaceLinks:links.length};}
const shapedRows=[];
await check('M02-SHAPED-CONVERGENCE',()=>{for(const delta of [.35,0]){const rows=[];for(const n of [33,65,129]){const c={...DEFAULT,delta},g=geometry(c,n),eq=equilibrium(basis(g),1.2,2,30000);assert.ok(eq.valid,eq.reason);assert.ok(eq.minF2>0&&eq.maxPsi>0);le(eq.currentError,T.shapedCurrentPressureRelative,'shaped current');le(eq.pressureError,T.shapedCurrentPressureRelative,'shaped pressure');le(eq.residual,T.shapedResidual,'shaped residual');eq.psi.forEach((p,k)=>{assert.ok(Number.isFinite(p));if(!g.mask[k])assert.equal(p,0);});let k=0;eq.psi.forEach((p,i)=>{if(p>eq.psi[k])k=i;});const d=distances(g,c),diag=Math.hypot(g.dr,g.dz);le(d.curveToInterface/diag,T.boundaryDistanceGridDiagonals,'curve to interface');le(d.interfaceToCurve/diag,T.boundaryDistanceGridDiagonals,'interface to curve');rows.push({delta,n,volume:g.volume,peakFlux:eq.maxPsi,axisR:g.R[k%n],axisZ:g.Z[Math.floor(k/n)],A:eq.A,B:eq.B,current:eq.current,meanPressure:eq.meanPressure,residual:eq.residual,minF2:eq.minF2,extent:{R:[g.R[0],g.R.at(-1)],Z:[g.Z[0],g.Z.at(-1)]},diag,boundary:d});}const mid=rows[1],fine=rows[2];fine.volumeChange=rel(fine.volume,mid.volume);fine.fluxChange=rel(fine.peakFlux,mid.peakFlux);fine.axisDisplacement=Math.hypot(fine.axisR-mid.axisR,fine.axisZ-mid.axisZ);le(fine.volumeChange,T.shaped65to129VolumeRelative,'shaped volume refinement');le(fine.fluxChange,T.shaped65to129PeakFluxRelative,'shaped flux refinement');le(fine.axisDisplacement/mid.diag,T.shapedAxisCoarseGridDiagonals,'shaped axis refinement');for(const key of ['volume','peakFlux']){const e1=Math.abs(rows[0][key]-rows[1][key]),e2=Math.abs(rows[1][key]-rows[2][key]);fine[key+'ObservedOrder']=e1>0&&e2>0?order(e1,e2):null;fine[key+'DifferenceRatio']=e2>0?e1/e2:null;}if(delta===0){fine.analyticEllipseVolume=2*Math.PI**2*1.66*.66**2*1.7;fine.ellipseVolumeRelative=rel(fine.volume,fine.analyticEllipseVolume);le(fine.ellipseVolumeRelative,T.ellipseFineVolumeRelative,'ellipse volume');}shapedRows.push(...rows);}return {rows:shapedRows,scope:'Staircase boundary distance and numerical refinement consistency. No global second-order or LCFS contour-accuracy claim.'};});
const cases=[['default',{}],['no-nbi',{nbi:0}],['no-gas',{gas:0}],['high-nbi',{nbi:8}],['high-gas',{gas:5}],['zero-aux-gas',{nbi:0,ech:0,gas:0}]];
function trace(c,dt,closure){const g=geometry(c),steps=[];const shot=runShot(c,g,dt,closure,s=>steps.push(s));return {c,dt:shot.dt,shot,steps};}
function rates(s,c,constant){const N=s.preN,We=s.preWe,Wi=s.preWi,V=s.volume,ne=N/V,te=We/(1.5*N*kev),t=s.t;const ip=t<1?.4+(c.ip-.4)*t:t>4?c.ip+(.4-c.ip)*(t-4):c.ip;const on=t>=1&&t<4,nbi=on?c.nbi:0,ech=on?c.ech:0;const tauE=constant?.tauE??.12*(ip/1.2)**.7*(c.bt/2)**.2*(Math.max(ne,1e18)/4e19)**.2*(Math.max(nbi+ech,.5)/5)**(-.35),tauP=constant?.tauP??1.6,eta=constant?.resistivity??2.8e-8*Math.max(te,.02)**(-1.5);
 const sourceGas=.3*c.gas*1e21,sourceBeam=.8*nbi*1e6/(80*kev),lossN=N/tauP,Pe=.8*.35*nbi*1e6+.9*ech*1e6,Pi=.8*.65*nbi*1e6,Pohm=eta*(2*Math.PI*1.66)**2/V*(ip*1e6)**2,Pbr=1.69e-38*ne**2*Math.sqrt(te*1000)*V,Pion=.0136*kev*.3*c.gas*1e21,Q=(We-Wi)/.25,Le=We/tauE,Li=Wi/tauE;
 return {N:[sourceGas,sourceBeam,-lossN],We:[Pe,Pohm,-Le,-Pbr,-Pion,-Q],Wi:[Pi,-Li,Q],thermal:[Pe,Pi,Pohm,-Le,-Li,-Pbr,-Pion],components:{sourceGas,sourceBeam,lossN,Pe,Pi,Pohm,Pbr,Pion,Q,Le,Li},ip,nbi,ech};}
const sums=x=>x.reduce((a,b)=>a+b,0),absSum=x=>sums(x.map(Math.abs));
function budgets(run,{continuity=true,constant}={}){const {steps,c}=run;assert.equal(steps.length,Math.round(5/run.dt));const initial={N:steps[0].initialN,We:steps[0].initialWe,Wi:steps[0].initialWi,thermal:steps[0].initialWe+steps[0].initialWi},total={N:0,We:0,Wi:0,thermal:0},scale={...total},worst={...total},worstTime={...total},componentTotals={};
 assert.equal(initial.N,3e19*run.shot.volume);assert.equal(initial.We,1.5*initial.N*kev*.5);assert.equal(initial.Wi,initial.We);const endpoint=run.shot.samples.at(-1),last=steps.at(-1);le(rel(last.postN,endpoint.ne*1e19*run.shot.volume),1e-15,'observed endpoint N');le(rel(last.postWe,endpoint.we*1e6),1e-15,'observed endpoint We');le(rel(last.postWi,endpoint.wi*1e6),1e-15,'observed endpoint Wi');steps.forEach((s,k)=>{assert.equal(s.volume,run.shot.volume);assert.equal(s.initialN,initial.N);assert.equal(s.initialWe,initial.We);assert.equal(s.initialWi,initial.Wi);assert.equal(s.step,k);assert.equal(s.t,k*run.dt);assert.equal(s.dt,run.dt);if(continuity){if(k){for(const key of ['N','We','Wi'])assert.equal(s['pre'+key],steps[k-1]['post'+key]);}else for(const key of ['N','We','Wi'])assert.equal(s['pre'+key],initial[key]);}const r=rates(s,c,constant);for(const [name,x]of Object.entries(r.components))componentTotals[name]=(componentTotals[name]||0)+x*s.dt;
 for(const key of ['N','We','Wi','thermal']){const pre=key==='thermal'?s.preWe+s.preWi:s['pre'+key],post=key==='thermal'?s.postWe+s.postWi:s['post'+key];const increment=sums(r[key])*s.dt,mag=absSum(r[key])*s.dt;const local=Math.abs(post-pre-increment)/Math.max(Math.abs(pre),mag);total[key]+=increment;scale[key]+=mag;const cumulative=Math.abs(post-initial[key]-total[key])/Math.max(initial[key],scale[key]);const err=Math.max(local,cumulative);if(err>worst[key]){worst[key]=err;worstTime[key]=s.t;}}});
 assert.equal(steps.length*run.dt,5);le(Math.abs(steps.at(-1).t+run.dt-5),2*Number.EPSILON*5,'floating endpoint coverage');return {worst,worstTime,componentTotals,total,stepCount:steps.length};}
function requireBudget(result){for(const [k,v]of Object.entries(result.worst))le(v,T.ledgerRelative,k+' independent ledger');}
const runs=new Map();
await check('M02-LEDGERS-INDEPENDENT',()=>{const constants=JSON.parse(fs.readFileSync(path.join(root,'science/constants.json'))).constants;assert.equal(constants.find(c=>c.id==='C-M01-KEV').value,kev);assert.equal(constants.find(c=>c.id==='C-M01-nbi_absorption').value,.8);assert.equal(constants.find(c=>c.id==='C-M01-gas_efficiency').value,.3);const rows=[];for(const [name,patch]of cases)for(const dt of [.002,.001]){const run=trace({...DEFAULT,...patch},dt);runs.set(name+':'+dt,run);const budget=budgets(run);requireBudget(budget);rows.push({case:name,dt,...budget});}const constant={tauE:.2,tauP:1.6,resistivity:2.8e-8},controlled=trace(DEFAULT,.002,{evaluate:()=>constant}),cb=budgets(controlled,{constant});requireBudget(cb);rows.push({case:'independent-constant-closure',dt:.002,...cb});const fake={preN:1e21,preWe:2e5,preWi:1e5,volume:20,t:2},c={...DEFAULT,nbi:4,ech:1,gas:2.5},hand=rates(fake,c).components;le(rel(hand.sourceGas,7.5e20),1e-15,'gas hand conversion');le(rel(hand.Pe,2.02e6),1e-15,'electron NBI/ECH hand conversion');le(rel(hand.Pi,2.08e6),1e-15,'ion NBI hand conversion');le(rel(hand.sourceBeam,2.496603629784305e20),1e-15,'beam hand conversion');assert.equal(hand.Q,4e5);return {rows,handCalculatedSourceChecks:hand,oracle:'Independent literal constants and pre-state equations; production errors, net increments, rates and closure not used.'};});
await check('M02-LEDGERS-NEGATIVE',()=>{const original=runs.get('default:0.002');assert.ok(original);const particle={...original,steps:original.steps.map(x=>({...x}))};particle.steps[100].postN+=1e-5*particle.steps[0].initialN;const p=budgets(particle,{continuity:false});assert.ok(p.worst.N>T.ledgerRelative);assert.throws(()=>requireBudget(p));const species={...original,steps:original.steps.map(x=>({...x}))};const shift=1e-5*species.steps[0].initialWe;species.steps[100].postWe+=shift;species.steps[100].postWi-=shift;const e=budgets(species,{continuity:false});assert.ok(e.worst.We>T.ledgerRelative&&e.worst.Wi>T.ledgerRelative);le(e.worst.thermal,T.ledgerRelative,'equal opposite mutation total budget');assert.throws(()=>requireBudget(e));return {particleMutation:p.worst,speciesMutation:e.worst,mutantCopiesOnly:true,continuityChecksDisabledForMutation:'Ensures independent rate balance itself rejects the copies, not just adjacent-state checks.'};});
await check('M02-PARTICLE-ANALYTIC',()=>{const rows=[.002,.001].map(dt=>{const r=runs.get('no-nbi:'+dt),s=r.steps.at(-1),expected=s.initialN*Math.exp(-5/1.6)+.3*r.c.gas*1e21*1.6*(1-Math.exp(-5/1.6));return {dt,expected,actual:s.postN,relative:rel(s.postN,expected)};});le(rows[0].relative,T.analyticParticleDt002Relative,'analytic particles');assert.ok(rows[1].relative<rows[0].relative);return {rows,observedOrder:order(rows[0].relative,rows[1].relative)};});
const checkpoints=[.5,1,2,2.5,3,4,4.5,5];
function checkpointValues(r){return checkpoints.map(t=>{const s=r.steps[Math.round(t/r.dt)-1];le(Math.abs(s.t+r.dt-t),1e-12,'checkpoint time');const {postN:N,postWe:We,postWi:Wi}=s;return {N,We,Wi,Te:We/(1.5*N*kev),Ti:Wi/(1.5*N*kev)};});}
await check('M02-TIMESTEP-CONVERGENCE',()=>{const rows=[];for(const name of ['default','zero-aux-gas']){const c={...DEFAULT,...cases.find(x=>x[0]===name)[1]},dtList=[.004,.002,.001,.0005],traces=dtList.map(dt=>runs.get(name+':'+dt)||trace(c,dt)),values=traces.map(checkpointValues);for(const vs of values)for(const v of vs)for(const x of Object.values(v))assert.ok(Number.isFinite(x)&&x>0);for(const key of ['N','We','Wi','Te','Ti']){const differences=[];for(let k=0;k<3;k++){const relative=values[k].map((v,i)=>Math.abs(v[key]-values[k+1][i][key])/Math.max(Math.abs(values[k+1][i][key]),1e-12));differences.push({max:max(relative),norm:Math.sqrt(sums(relative.map(x=>x*x)))});}le(differences[2].max,T.timeFineDifferenceRelative,'fine timestep '+key);const orders=[];for(let k=0;k<2;k++){if(differences[k].max<=T.timeRoundoffRelative&&differences[k+1].max<=T.timeRoundoffRelative)orders.push('roundoff-limited');else{const p=order(differences[k].norm,differences[k+1].norm);assert.ok(p>=T.timeObservedOrder[0]&&p<=T.timeObservedOrder[1],`${name} ${key} time order ${p}`);orders.push(p);}}rows.push({case:name,component:key,differences,orders});}}return {timesteps:[.004,.002,.001,.0005],checkpoints,rows};});
await check('M02-STABILITY-GUARDS',()=>{const rows=[];let coarse,fine;for(const dt of [.01,.005,.002,.001]){const r=trace(DEFAULT,dt),b=budgets(r);requireBudget(b);for(const s of r.steps)for(const x of [s.postN,s.postWe,s.postWi])assert.ok(Number.isFinite(x)&&x>0);rows.push({dt,...b});if(dt===.01)coarse=checkpointValues(r);if(dt===.001)fine=checkpointValues(r);}const differences={};for(const key of ['N','We','Wi']){differences[key]=max(coarse.map((v,i)=>rel(v[key],fine[i][key])));le(differences[key],T.stabilityCoarseDifferenceRelative,'coarse stability '+key);}assert.throws(()=>trace(DEFAULT,.002,{evaluate:()=>({tauE:1e-4,tauP:1.6,resistivity:2.8e-8})}),/valid thermal-plasma regime/);for(const dt of [0,-.001,NaN,.010001])assert.throws(()=>runShot(DEFAULT,geometry(DEFAULT),dt));assert.throws(()=>runShot(DEFAULT,geometry(DEFAULT),.002,undefined,()=>{throw Error('observer sentinel');}),/observer sentinel/);
 const r=trace(DEFAULT,.003),b=budgets(r);requireBudget(b);assert.equal(r.dt,5/Math.round(5/.003));assert.equal(r.shot.samples.at(-1).t,5);assert.ok(!r.shot.samples.some(s=>s.t===1||s.t===4));for(const sample of r.shot.samples){const reference=rates({...r.steps[0],t:sample.t},DEFAULT);assert.equal(sample.nbi,reference.nbi);assert.equal(sample.ech,reference.ech);assert.equal(sample.ip,reference.ip);}const heldOut=[];for(const patch of [{bt:1,delta:-.3},{ip:2,kappa:1.95},{nbi:11.25,gas:.7}]){const run=trace({...DEFAULT,...patch},.002);const result=budgets(run);requireBudget(result);heldOut.push({controls:patch,worst:result.worst});}return {baseline:rows,coarseRelativeDifferences:differences,invalidDtRejected:[0,-.001,'NaN',.010001],stiffClosureRejected:true,observerExceptionsPropagate:true,unaligned:{requestedDt:.003,actualDt:r.dt,...b},heldOut,scope:'Numerical state validity only; no plasma stability inference.'};});
await check('M02-EXISTING-TESTS',()=>{const old=execFileSync('git',['show','b07537877cec168d20783a3cfc45366fccbd4538:tests/physics.test.mjs'],{cwd:root});assert.equal(hash(old),hash(fs.readFileSync(path.join(root,'tests/physics.test.mjs'))));const out=spawnSync(process.execPath,['--experimental-strip-types','--test','tests/physics.test.mjs'],{cwd:root,encoding:'utf8'});assert.equal(out.status,0,out.stdout+out.stderr);return {unchangedTestSha256:hash(old),exitCode:out.status,output:out.stdout+out.stderr};});
await check('M02-SCIENTIFIC-SCOPE',()=>{const lock=JSON.parse(fs.readFileSync(path.join(root,'validation/science-lock.json'))),files=[];for(const [file,digest]of Object.entries(lock.files)){assert.equal(hash(fs.readFileSync(path.join(root,file))),digest);files.push({file,sha256:digest});}assert.equal(MACHINE.R,1.66);assert.equal(MACHINE.a,.66);const s=runShot(DEFAULT,geometry(DEFAULT));assert.equal(s.modelVersion,'0.1.0');assert.equal(s.schemaVersion,1);assert.equal(hash(fs.readFileSync(path.join(root,'specs/proposals/m02.md'))),spec.normativeMarkdownHash);const engine=fs.readFileSync(path.join(root,'physics/engine.ts'),'utf8'),old=execFileSync('git',['show','b07537877cec168d20783a3cfc45366fccbd4538:physics/engine.ts'],{cwd:root,encoding:'utf8'});for(const fragment of ['export const educationalTransport:TransportClosure=','export function waveform(']){const line=old.split('\n').find(x=>x.startsWith(fragment));assert.ok(engine.includes(line),'Unchanged closure/waveform');}return {scienceFiles:files,physicsModelVersion:s.modelVersion,exportSchema:s.schemaVersion,sourceReview:'Engine diff limited to optional inactive-node boundaries and immutable observer. Existing numerical update, SOR arithmetic, closure, waveform, constants and default output unchanged.',limitations:['Analytic rectangle is a verification domain, not a new LCFS.','Shaped-mask study does not establish global second-order boundary accuracy.','Independent ledgers establish discrete thermal/particle equation consistency, not whole-machine or experimental accuracy.','Numerical state-validity checks do not establish MHD stability, disruption prediction or facility operating safety.','Fine-grid quartic identity is cancellation-sensitive in double precision (about 9.20e-7 relative against the 1e-6 gate); endpoint construction and runtime are recorded.']};});
if(process.argv.includes('--final')){
 await check('M02-TYPECHECK',()=>{const r=spawnSync(path.join(root,'node_modules/.bin/tsc'),['--noEmit'],{cwd:root,env:{...process.env,PATH:path.dirname(process.execPath)+':'+process.env.PATH},encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);return {exitCode:r.status,output:r.stdout+r.stderr};});
 await check('M02-BUILD',()=>{const r=spawnSync(path.join(root,'node_modules/.bin/vinext'),['build'],{cwd:root,env:{...process.env,PATH:path.dirname(process.execPath)+':'+process.env.PATH},encoding:'utf8',timeout:180000,maxBuffer:10*1024*1024});assert.equal(r.status,0,r.stdout+r.stderr);return {exitCode:r.status,output:r.stdout+r.stderr};});
 assert.equal(fingerprint(),sourceHash,'Source changed during final checks');
 const report={role:'validation',agentId:'/root/validation',implementationAgentId:'/root/software',status:records.length===spec.requiredChecks.length&&records.every(r=>r.status==='PASS')?'PASS':'FAIL',sourceFingerprint:sourceHash,checks:spec.requiredChecks.map(name=>{const r=records.find(x=>x.name===name);assert.ok(r,'Missing '+name);return r;}),findings:records.filter(r=>r.status!=='PASS').map(r=>({check:r.name,evidence:r.evidence})),gridConvergence,shapedConvergence:shapedRows,limitations:['Numerical verification of unchanged educational M01 model; no experimental validation.','Analytic rectangular boundary is not an LCFS or hardware geometry.','Shaped staircase refinement has no global second-order accuracy claim.','Balances cover tracked particles and thermal energies only.','Stability means tested numerical state validity, not plasma MHD stability.','Fine-grid quartic stencil identity is cancellation-sensitive in double precision: about 9.20e-7 relative against the locked 1e-6 limit; endpoint construction and runtime are recorded.'],independentTestSha256:hash(fs.readFileSync(path.join(root,'validation/independent/m02.mjs')))};fs.writeFileSync(path.join(root,'validation/m02-report.json'),JSON.stringify(report,null,2)+'\n');console.log('FINAL REPORT '+report.status+' '+sourceHash);
}
process.exitCode=records.some(r=>r.status!=='PASS')?1:0;
