import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {execFileSync,spawnSync} from 'node:child_process';import {pathToFileURL} from 'node:url';import {createRequire} from 'node:module';
import {root,hash,fingerprint} from '../../tools/workflow.mjs';import {validateCapabilityPolicy} from '../../tools/capability-policy.mjs';
const sourceFingerprint=fingerprint(),checks=[],require=createRequire(path.join(root,'package.json'));
async function check(name,fn){let status='PASS',measurements;try{measurements=await fn();}catch(e){status='FAIL';measurements={failure:e.message,stack:e.stack};}const evidence=`validation/evidence/${name}.json`;fs.writeFileSync(path.join(root,evidence),JSON.stringify({name,status,sourceFingerprint,runtimeVersion:process.version,measurements},null,2)+'\n');checks.push({name,status,evidence,sha256:hash(fs.readFileSync(path.join(root,evidence)))});console.log(name+': '+status+(status==='FAIL'?' '+measurements.failure:''));}
await check('CAPABILITY-POLICY',async()=>{const policy=JSON.parse(fs.readFileSync(path.join(root,'science/capability-policy.json'))),historical=[];for(const m of ['infrastructure','m02']){const spec=JSON.parse(fs.readFileSync(path.join(root,`specs/${m}.json`))),approval=JSON.parse(fs.readFileSync(path.join(root,`validation/${m}-approval.json`)));assert.equal(hash(JSON.stringify(spec)),policy.legacySpecHashes[m]);assert.equal(approval.specHash,policy.legacySpecHashes[m]);assert.deepEqual(validateCapabilityPolicy(spec,{root,policy}),{status:'PASS',errors:[],legacyExemption:true});const altered={...spec,maintenanceMutation:true};const result=validateCapabilityPolicy(altered,{root,policy});assert.equal(result.status,'FAIL');assert.equal(result.legacyExemption,false);historical.push({milestone:m,exactHash:approval.specHash,mutationRejected:true});}
const developer=spawnSync(process.execPath,['--test','tests/capability-policy.test.mjs'],{cwd:root,encoding:'utf8'});assert.equal(developer.status,0,developer.stdout+developer.stderr);
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'independent-policy-'));const put=(p,x)=>{const absolute=path.join(dir,p);fs.mkdirSync(path.dirname(absolute),{recursive:true});fs.writeFileSync(absolute,typeof x==='string'?x:JSON.stringify(x));};const cases=[];
try{const lock=JSON.parse(fs.readFileSync(path.join(root,'validation/science-lock.json')));for(const p of ['tools/workflow.mjs','tools/capability-policy.mjs','science/capability-policy.json','validation/science-lock.json',...Object.keys(lock.files)])put(p,fs.readFileSync(path.join(root,p),'utf8'));execFileSync('git',['init','-q'],{cwd:dir});const w=await import(pathToFileURL(path.join(dir,'tools/workflow.mjs')).href);
const artifact=(p,text)=>{put(p,text);return {path:p,sha256:hash(text)};};const cap={id:'future-fixture',verification:{testPath:'tests/future.mjs',checkName:'VERIFY'},experimentalValidationPlan:artifact('specs/experiment.md','# Held-out experiment plan'),uncertaintyModel:artifact('specs/uncertainty.md','# Input and model discrepancy model'),domainOfValidity:artifact('specs/domain.md','# Supported parameter domain'),referenceComparison:artifact('specs/reference.json',JSON.stringify({availability:'available',implementations:[{name:'Reference',versionOrRevision:'1',source:'https://example.org/reference',comparisonPlan:'Compare declared observables on matched inputs'}]}))};put('tests/future.mjs','// fixture verification implementation');put('validation/evidence/verify.txt','independent fixture evidence');const original={id:'fixture',physicsCapabilityChange:true,physicsCapabilities:[cap],requiredChecks:['VERIFY']};
function prepare(spec,review=true){put('specs/fixture.json',spec);put('validation/fixture-approval.json',{role:'director',specHash:hash(JSON.stringify(spec)),...(review?{capabilityPolicyReview:{status:'REVIEWED'}}:{})});put('validation/fixture-report.json',{role:'validation',agentId:'validator',implementationAgentId:'implementer',status:'PASS',sourceFingerprint:w.fingerprint(),checks:[{name:'VERIFY',status:'PASS',evidence:'validation/evidence/verify.txt',sha256:hash('independent fixture evidence')}]});}
function expect(label,status,pattern){const r=w.gate('fixture');assert.equal(r.status,status,label+JSON.stringify(r));if(pattern)assert.ok(r.errors.some(x=>pattern.test(x)),label);cases.push({label,...r});}
prepare(original);expect('complete package accepted by workflow gate','PASS');prepare(original,false);expect('missing Director scientific review','FAIL',/Director capability/);
for(const field of ['verification','experimentalValidationPlan','uncertaintyModel','domainOfValidity','referenceComparison']){const s=structuredClone(original);delete s.physicsCapabilities[0][field];prepare(s);expect('missing '+field,'FAIL',new RegExp(field==='verification'?'verification':field));}
const wrong=structuredClone(original);wrong.physicsCapabilities[0].uncertaintyModel.sha256='0'.repeat(64);prepare(wrong);expect('wrong artifact digest','FAIL',/hash mismatch/);
fs.unlinkSync(path.join(dir,'tests/future.mjs'));assert.equal(w.capabilityGate(original,'approval').status,'PASS');prepare(original);expect('planned test cannot be accepted before implementation','FAIL',/verification test/);put('tests/future.mjs','// fixture verification implementation');
const invalid=structuredClone(original);invalid.physicsCapabilities[0].referenceComparison=artifact('specs/reference.json',JSON.stringify({availability:'none_identified',rationale:'No implementation'}));prepare(invalid);expect('undocumented reference exception','FAIL',/search records/);
return {historical,workflowIntegration:cases,developerTests:developer.stdout+developer.stderr,limitation:'Mechanical completeness and hash integrity are tested; scientific adequacy is explicitly delegated to Director review, not inferred from nonempty files.'};}finally{fs.rmSync(dir,{recursive:true,force:true});}});
await check('DASHBOARD-READABILITY',()=>{const file=path.join(root,'app/validation/page.tsx'),source=fs.readFileSync(file,'utf8'),css=fs.readFileSync(path.join(root,'app/validation/validation.css'),'utf8'),ts=require('typescript'),react=require('react'),server=require('react-dom/server');let state=[];const mockReact={...react,useEffect:()=>{},useState:()=>[state.shift(),()=>{}]};const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText;const mod={exports:{}};new Function('require','module','exports',js)((name)=>name==='react'?mockReact:name.endsWith('.css')?{}:require(name),mod,mod.exports);
const full=JSON.parse(fs.readFileSync(path.join(root,'public/validation-results.json')));const render=(report,attention=false,loaded=true,error='')=>{state=[report,loaded,error,attention];return server.renderToStaticMarkup(react.createElement(mod.exports.default));};const html=render(full);const percent=v=>(v*100).toLocaleString('en-US',{maximumSignificantDigits:4})+'%';for(const g of full.gridConvergence){assert.ok(html.includes(percent(g.Linf)));assert.ok(html.includes(percent(g.L2)));}for(const x of ['Magnetic equilibrium','Particle &amp; energy balances','Regression &amp; reliability','What remains unvalidated','has not been validated against experimental DIII-D shots','Technical evidence and exact acceptance limits','Saved snapshot'])assert.ok(html.includes(x),x);assert.ok(html.includes('aria-pressed="true"'));assert.match(css,/@media\(max-width:600px\)/);assert.match(css,/focus-visible/);assert.match(css,/overflow-x:auto/);
const pass={...full,status:'PASS',directorDecision:'ACCEPTED'};assert.ok(render(pass).includes('Accepted — numerical checks passed'));assert.ok(render({...pass,directorDecision:'REJECTED'}).includes('Awaiting acceptance'));assert.ok(!render(null).includes('Accepted —'));assert.ok(render(null,false,false).includes('Loading saved evidence'));assert.ok(render(null,false,true,'unavailable').includes('role="alert"'));
const fail={...pass,status:'FAIL',checks:pass.checks.map((x,i)=>i===0?{...x,status:'FAIL'}:x)};assert.ok(render(fail).includes('Review required'));const filtered=render(fail,true);assert.ok(filtered.includes(fail.checks[0].name));assert.ok(!filtered.includes('>'+fail.checks[1].name+'</strong>'));assert.ok(filtered.includes('Needs attention (1)'));const inconclusive={...pass,status:'INCONCLUSIVE',checks:pass.checks.map((x,i)=>i===0?{...x,status:'INCONCLUSIVE'}:x)};assert.ok(!render(inconclusive).includes('Accepted —'));assert.ok(render(inconclusive,true).includes('Inconclusive'));assert.ok(render(pass,true).includes('No recorded checks need attention.'));const missing={...pass,gridConvergence:[]};assert.ok(render(missing).includes('No grid measurements recorded.'));
const report=JSON.parse(fs.readFileSync(path.join(root,'validation/m02-report.json')));assert.deepEqual(full.gridConvergence,report.gridConvergence);const snapshots=JSON.parse(fs.readFileSync(path.join(root,'experiments/baseline/infrastructure-start-source.json')));const physicsHashes=Object.fromEntries(['physics/engine.ts','physics/api.ts','physics/verification.ts'].map(p=>[p,hash(fs.readFileSync(path.join(root,p)))]));return {sourceSha256:hash(source),stylesheetSha256:hash(css),renderedStateTests:['saved evidence numeric percentages','all three readable check groups','complete supporting evidence disclosures','accepted','rejected decision','missing report','loading','network error','failed check filtering','inconclusive filtering','zero attention','missing metrics'],physicsHashes,limitations:['React static render verifies content and branching, not browser layout or interaction. No browser QA performed.','Snapshot evidence is explicitly identified; displayed metrics are derived from recorded fields without invented values.']};});
if(process.argv.includes('--complete')){await check('CURRENT-M02-VALIDATION',()=>{const r=JSON.parse(fs.readFileSync(path.join(root,'validation/m02-report.json')));assert.equal(r.status,'PASS');assert.equal(r.sourceFingerprint,sourceFingerprint);assert.equal(r.checks.length,16);for(const c of r.checks){assert.equal(c.status,'PASS');assert.equal(hash(fs.readFileSync(path.join(root,c.evidence))),c.sha256);}return {reportSha256:hash(fs.readFileSync(path.join(root,'validation/m02-report.json'))),checks:r.checks,physicsUnchanged:'Full same-runtime M01 regression and immutable science registry checks pass in refreshed M02 validation.'};});assert.equal(fingerprint(),sourceFingerprint);const report={role:'validation',agentId:'/root/validation',implementationAgentId:'/root',status:checks.every(c=>c.status==='PASS')?'PASS':'FAIL',sourceFingerprint,checks,findings:checks.filter(c=>c.status!=='PASS').map(c=>({check:c.name,evidence:c.evidence})),limitations:['Dashboard assessment used source review and React static rendering, not browser visual QA.','Capability gate checks structural completeness; Director remains responsible for scientific adequacy.']};fs.writeFileSync(path.join(root,'validation/readability-policy-report.json'),JSON.stringify(report,null,2)+'\n');}
process.exitCode=checks.some(c=>c.status!=='PASS')?1:0;
